In [ ]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
### sentences
sent=[
    'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good girl',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [21]:
# vocab size:
voc_size = 100

In [22]:
# one hot representation:
from tensorflow.keras.preprocessing.text import one_hot


one_hot_repo = [one_hot(words, voc_size) for words in sent]
print(one_hot_repo)

[[10, 47, 73, 45], [10, 47, 73, 24], [10, 64, 73, 97], [76, 85, 77, 64, 80], [76, 85, 77, 64, 17], [27, 10, 2, 73, 48], [80, 5, 93, 64]]


In [23]:
# Word embedding representation:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [25]:
# pre padding the sequences based on the max lenght of the sentence

sent_len = max([len(text) for text in sent])
print("maximum sentence length", sent_len)

embedded_docs = pad_sequences(one_hot_repo, padding="pre", maxlen=8)
print(embedded_docs)

maximum sentence length 31
[[ 0  0  0  0 10 47 73 45]
 [ 0  0  0  0 10 47 73 24]
 [ 0  0  0  0 10 64 73 97]
 [ 0  0  0 76 85 77 64 80]
 [ 0  0  0 76 85 77 64 17]
 [ 0  0  0 27 10  2 73 48]
 [ 0  0  0  0 80  5 93 64]]


In [26]:
  # dimensionality of feature space:
  dim = 10

  model = Sequential()
  model.add(Embedding(voc_size, 10, input_length=8))
  model.compile("adam", "mse")

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             1000      
                                                                 
Total params: 1000 (3.91 KB)
Trainable params: 1000 (3.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
# the glass of milk:
embedded_docs[0]

array([ 0,  0,  0,  0, 10, 47, 73, 45], dtype=int32)

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[-0.01677557,  0.03299003, -0.0186121 ,  0.02193265, -0.04520833,
         0.03165983, -0.01471316,  0.01894556, -0.01451863,  0.02392128],
       [-0.01677557,  0.03299003, -0.0186121 ,  0.02193265, -0.04520833,
         0.03165983, -0.01471316,  0.01894556, -0.01451863,  0.02392128],
       [-0.01677557,  0.03299003, -0.0186121 ,  0.02193265, -0.04520833,
         0.03165983, -0.01471316,  0.01894556, -0.01451863,  0.02392128],
       [-0.01677557,  0.03299003, -0.0186121 ,  0.02193265, -0.04520833,
         0.03165983, -0.01471316,  0.01894556, -0.01451863,  0.02392128],
       [-0.00720229,  0.01513748, -0.0218393 , -0.0117363 , -0.04886066,
        -0.0269899 ,  0.00358529,  0.02911979,  0.00157863, -0.04853464],
       [ 0.04718852,  0.02936572,  0.04622242,  0.04701862, -0.0285779 ,
         0.0441618 , -0.02152087, -0.00475911, -0.02696202, -0.02393624],
       [ 0.04767667,  0.00197822, -0.02165102,  0.02138964, -0.03157143,
         0.0378775 ,  0.01382214, -0.03421252

In [30]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [32]:
vocab_size=500

one_hot = [one_hot(word, vocab_size) for word in sent]
print(one_hot)

[[11, 457, 480, 490, 376, 78], [366, 418, 480, 114, 131, 499], [136, 374, 130, 338], [11, 214, 480, 357, 11, 468], [201, 132, 171, 480, 114, 131, 499], [232, 480, 114, 131, 444, 309]]


In [35]:
embedded_doc = pad_sequences(one_hot, maxlen=12, padding='pre')
print(embedded_doc)

[[  0   0   0   0   0   0  11 457 480 490 376  78]
 [  0   0   0   0   0   0 366 418 480 114 131 499]
 [  0   0   0   0   0   0   0   0 136 374 130 338]
 [  0   0   0   0   0   0  11 214 480 357  11 468]
 [  0   0   0   0   0 201 132 171 480 114 131 499]
 [  0   0   0   0   0   0 232 480 114 131 444 309]]


In [37]:
dimension = 10

model = Sequential()
model.add(Embedding(vocab_size, dimension, input_length=12))
model.compile('adam', 'mse')

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 12, 10)            5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
model.predict(embedded_doc[0])

1/1 [==============================] - 0s 33ms/step


array([[ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
         1.0775007e-02, -3.6354125e-02,  2.4775241e-02,  4.8154164e-02,
        -3.9886642e-02,  1.7937336e-02],
       [ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
         1.0775007e-02, -3.6354125e-02,  2.4775241e-02,  4.8154164e-02,
        -3.9886642e-02,  1.7937336e-02],
       [ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
         1.0775007e-02, -3.6354125e-02,  2.4775241e-02,  4.8154164e-02,
        -3.9886642e-02,  1.7937336e-02],
       [ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
         1.0775007e-02, -3.6354125e-02,  2.4775241e-02,  4.8154164e-02,
        -3.9886642e-02,  1.7937336e-02],
       [ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
         1.0775007e-02, -3.6354125e-02,  2.4775241e-02,  4.8154164e-02,
        -3.9886642e-02,  1.7937336e-02],
       [ 2.7759783e-03, -2.4923563e-02, -2.4720693e-02,  9.8040923e-03,
   